spring.application.name=Ai_based_resume_generator

server.port=8080

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/resume_db
spring.datasource.username=postgres
spring.datasource.password=12345

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

#create table in database when project is started
spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=

gemini.api.key=AIzaSyDfU5uFyW1NS5LLzND5eExRS_5btkDIsUY

